---
#Change the name of the file to settings.yaml
usegalaxy_instances:
  - name: usegalaxy_EX
    url: usegalaxy.examples
    api: very_ikey #can be left empty, not for now though
    endpoints:
      - changeme
      - changeme
    #The deafult compute is usually found in
    #infrastructure-playbook/files/galaxy/config/user_preferences_extra_conf.yml
    default_compute_id: "None" 
    maxwait: integer_upload_timeout
ga_path: /absolute/path
data_inputs:
  label_example_name: # Change this key accordingly to the workflow file
    url: change_me
    file_type: change_me
timeout: 1200
